name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Core Docker image
      run: docker build . --file Dockerfile --tag mdzik/tclb_core:$(date +%s)
