name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./core/ubuntu2004
          platforms: linux/amd64
          tags: mdzik/tclb_core:latest,mdzik/tclb_core:${{ steps.date.outputs.date }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
