name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./core/ubuntu2004
          platforms: linux/amd64
          tags: mdzik/tclb_core:latest,mdzik/tclb_core:${{date +%s}}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            
            
#    - uses: actions/checkout@v2
#    - name: Build the Core Docker image
 #     run: cd ./core/ubuntu2004 && docker build . --file Dockerfile --tag mdzik/tclb_core:$(date +%s)
         
