name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:

      - 'workSpace/**'
jobs:

  build-workspace:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      -
        name: Build Workspace
        uses: docker/build-push-action@v2
        with:
          context: ./workSpace/ubuntu2004
          platforms: linux/amd64
          push: true
          tags: mdzik/tclb_workspace:latest,mdzik/tclb_workspace:${{ steps.date.outputs.date }}
